### ISSUE TITLE
Error: No file named "icon.png"

### ISSUE THREAD

**Issue by waitimconfused** [YellowSquash262/Multi-Layer-Noise-Terrain-Generator#1]
I think you forgot to give the image used. In the main branch, this image is not included.
Below is the error the script returns:

```
  File "C:\███████████████\main.py", line 92, in <module>
    icon1 = pygame.image.load('icon.png')
FileNotFoundError: No file 'icon.png' found in working directory 'C:\███████████████'.
```
_(File locations blured for privacy)_

Also, after substituting the "icon.png" with the image from your [replit](https://replit.com/@YellowSquash262/Multi-layer-noise-Terrain-simulator#icon.png), the application launched soon freezes.

Would you be able to fix this?

**Comment by waitimconfused** [comment]
Never mind. I messed something up when copying the files to test.

**Comment by Max-Carson** [comment]
Hey its YellowSquash262. Sorry I never got back to you, I saw that you figured it out. Just letting you know that if you have any more questions or would like me to add something i'd be happy to help. Happy to see someone using my project :)

**Comment by waitimconfused** [comment]
No, I don’t have any more questions, thanks though!
